# Generated by Django 4.1.3 on 2022-11-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
